# railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[env]
PORT = "4000"
SECRET_KEY_BASE = "your-secret-key-base"
DATABASE_URL = "postgresql://user:pass@host:port/db"
MP_ACCESS_TOKEN = "your-mercadopago-access-token"
MP_PUBLIC_KEY = "your-mercadopago-public-key"
PHX_HOST = "your-app.railway.app"