defmodule LauraWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :laura

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_laura_key",
    signing_salt: "HtOw+V2l",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :laura,
    gzip: not code_reloading?,
    only: LauraWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :laura
  else
    # # ⚠️ ESTE ES EL CÓDIGO DE PRODUCCIÓN:
    # plug Plug.Static,
    #   at: "/",
    #   # Debe apuntar a la carpeta donde `mix assets.deploy` guarda los archivos
    #   from: :laura,
    #   # **MUY IMPORTANTE:** Esto usa el archivo `cache_manifest.json` generado
    #   # por `phx.digest` para servir los archivos con nombres de hash (ej: app-XYZ.css)
    #   gzip: true,
    #   only: ~w(assets fonts images favicon.ico robots.txt),
    #   cache_manifest: "priv/static/cache_manifest.json"
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LauraWeb.Router
end
